name: Sincronizar Repositorio con Cuenta B

on:
  push:
    branches:
      - main

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código actual
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Reflejar cambios en Cuenta B
        run: |
          REMOTE_REPO="https://x-access-token:${{ secrets.CUENTA_B_TOKEN }}@github.com/AMG0-EXP-totem01amg0-rgb/PSCQube_amg0.git"
          git push --mirror "$REMOTE_REPO"
