name: Sincronizar Repositorio con Cuenta B

on:
  push:
    branches:
      - main # Se ejecuta automáticamente al empujar cambios a main

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código actual (Cuenta A)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Trae todo el historial de commits y ramas, necesario para el mirror

      - name: Reflejar cambios en Cuenta B
        run: |
          # Reemplaza 'ORGANIZACION_O_USUARIO_B' y 'NOMBRE_REPO_B' con los datos reales de la Cuenta B
          REMOTE_REPO="https://x-access-token:${{ secrets.CUENTA_B_TOKEN }}@github.com/AMG0-EXP-totem01amg0-rgb/PSCQube_amg0"
          
          # Realiza un push espejo que actualiza commits, ramas y etiquetas por completo
          git push --mirror "$REMOTE_REPO"
